#!/bin/bash

xbps-install -Syu intel-media-driver intel-video-accel linux-firmware-intel mesa-intel-dri mesa-vulkan-intel vulkan-loader

mkdir -pv /etc/X11/xorg.conf.d
cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
	Identifier "Intel Graphics"
	Driver "modesetting"
EndSection
EOF

rm /home/$_user/.config/autostart/autointelvga.desktop
