#!/bin/bash

clear
echo "Connected HDD drives"
echo "--------------------"
lsblk -dno MODEL,SIZE,TRAN,NAME,MOUNTPOINT | grep -v usb
echo ""
read -p "Target drive (sdx): " targetdrive
echo ""

dd if=$1 of=/dev/$targetdrive status=progress
echo ""

echo "Syncing.."
sync
echo "Syncing complete"
echo "Exiting"
sleep 2
exit
