#!/bin/bash

clear
echo "Connected USB drives"
echo "--------------------"
lsblk -dno MODEL,SIZE,TRAN,NAME,MOUNTPOINT | grep usb
echo ""
read -p "Target drive (sdx): " targetdrive
echo ""

isohybrid $1 >/dev/null 2>&1
dd if=$1 of=/dev/$targetdrive status=progress
echo ""

echo "Syncing.."
sync
echo "Syncing complete"
echo "Exiting"
sleep 2
exit

