#!/bin/bash

chromeinstall=$(mktemp -d)
cd $chromeinstall
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
rpm2cpio google-chrome-stable_current_x86_64.rpm | cpio -idmv
cp -r etc opt usr /

