#!/bin/bash

_user="$(who|awk 'NR==1 {print $1}')"
xbps-install -Syu virtualbox-ose virtualbox-ose-dkms virtualbox-ose-guest-dkms linux5.15-headers
virtualboxinstalltmp=(mktemp -d)
cd virtualboxinstalltmp
wget https://download.virtualbox.org/virtualbox/6.1.32/Oracle_VM_VirtualBox_Extension_Pack-6.1.32.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.32.vbox-extpack
usermod -aG vboxusers $_user
